apiVersion: v1
kind: Service
metadata:
  name: ms-seller-service
  labels:
    app: ms-seller
spec:
  selector:
    app: ms-seller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
